# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
   - group: epaycoDev

stages:
  - stage: Build
    displayName: Build iOS QA
    jobs:
      # Debug buildg
      - job: Build_Ios_QA
        variables:
          - name: SDK
            value: iphoneos
          - name: Configuration
            value: Release
        displayName: Build QA
        steps:
        - task: Xcode@5
          inputs:
            actions: 'build'
            scheme: ''
            sdk: $(SDK)
            configuration: $(Configuration)
            xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
            xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
